dataset:
  type: csv # or csv
  path: datasets/homeloan_train.xls
  continuous_features: ['ApplicantIncome','CoapplicantIncome','LoanAmount', 'Loan_Amount_Term', 'Credit_History']
  categorical_features: ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area']
  target: Loan_Status

constraints_file: config/constraints_conf_no.json
output_folder: results

model:
  model_type: classification
  model_backend: sklearn
  state: pretrained
  name: LogisticRegression
  path: models/homeloan_logistic_model.pkl
  categorical_features_encoding: onehot # 
  continuous_features_normalization: minmax # standart

search:
  algorithm: genetic #random
  loss: hinge
  continuous_distance: diffusion # l1
  categorical_distance: hamming # l1
  sparsity: False # True
  coherence: False # True
  search_normalization: False # standart
  weights: [0.5, 0.5, 0.5] # loss, distance, coherence TODO add sparsity