spartsity:  0.5
initialization: random

dataset:
  type: csv # or csv
  path: datasets/homeloan_clean.csv
  continuous_features: ['ApplicantIncome','CoapplicantIncome','LoanAmount', 'Loan_Amount_Term', 'Credit_History']
  categorical_features: ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area']
  target: Loan_Status

feature_manager:
  categorical_features:
    encoding: onehot # freqhot
  continuous_features:
    normalization: standard #minmax
  constraints:
    feature_x: []

model:
  type: sklearn
  state: pretrained
  name: LogisticRegression
  path: models/logistic_regression.pkl