spartsity:  0.5
initialization: random

dataset:
  type: csv
  path: homeloan_data.csv

feature_manager:
  categorical_features:
    encoding: onehot # freqhot
  continuous_features:
    normalization: standard #minmax
  constraints:
    feature_x: []

model:
  type: sklearn
  state: pretrained
  name: LogisticRegression
  path: models/logistic_regression.pkl