dataset:
  type: csv # or csv
  path: data/bikes_train.csv
  continuous_features: [ "temperature", "feeling_temperature", "humidity", "wind_speed", "season", "weather", "year", "month", "week_day" ]
  categorical_features: [ "holiday", "working_day" ]
  target: "y"

constraints_file: cfe/constraints_conf_bikes.json
output_folder: cfe/output

model:
  model_type: regression
  model_backend: sklearn
  state: pretrained
  name: LinearRegression
  path: data/bikes_model_linear_regression.pkl
  categorical_features_encoding: label_encoder # Possible values: [onehot, label_encoder, frequency]
  continuous_features_normalization: standard # Possible values: [minmax, standard]

cfsearch:
  optimizer: genetic # Possible values: [random, CPLEX, genetic], currently supported genetic
  loss_type: MSE
  continuous_distance:
    type: diffusion # Possible values: [weighted_l1, diffusion]
    diffusion_params:
      k_neighbors: 8  # the size of the local neighborhood around each point, median of the pairwise distances among a random sample of your data points.
      alpha: 1 # how many dimensions or features of the diffusion space you want to consider
      diffusion_normalization: True # standard
    weighted_l1_params:
      weights: [ 1, 1, 1, 1 ]
  categorical_distance: hamming # l1
  sparsity_penalty:
    type: elastic_net
    alpha: 0.5
    beta: 0.5
  sparsity: False # True
  coherence: True # False # True
  search_normalization: False # standard
  search_encoding: False # frequency
  objective_function_weights: [ 0.5, 0.5, 0.5 ] # loss, distance, coherence TODO add sparsity
  feature_weights: False