dataset:
  type: csv # or csv
  path: datasets/compas_ordered_features.csv
  continuous_features: ['age', 'priors_count', 'days_b_screening_arrest', 'length_of_stay']
  categorical_features: ['age_cat', 'sex', 'race', 'c_charge_degree', 'is_recid', 'is_violent_recid', 'two_year_recid']
  target: class

constraints_file: config/constraints_compas.json
output_folder: results

model:
  model_type: classification
  model_backend: sklearn # Possible values: [tensorflow, sklearn]
  state: pretrained
  name: LogisticRegression
  path: models/compas_logistic_model.pkl
  categorical_features_encoding: False # Possible values: [onehot, label_encoder, frequency]
  continuous_features_normalization: False # Possible values: [minmax, standard]

cfsearch:
  optimizer: genetic # Possible values: [random, CPLEX, genetic], currently supported genetic
  loss_type: hinge
  continuous_distance:
    type: diffusion # Possible values: [weighted_l1, diffusion]
    diffusion_params:
      k_neighbors: 10  # the size of the local neighborhood around each point, median of the pairwise distances among a random sample of your data points.
      alpha: 1 # how many dimensions or features of the diffusion space you want to consider
      diffusion_normalization: False # standard
    weighted_l1_params:
      weights: [1, 1, 1, 1]
  categorical_distance: hamming # l1
  sparsity: True # Possible values: [True, False]
  coherence: True # Possible values: [True, False]
  search_normalization: False # standard
  search_encoding: False # frequency
  objective_function_weights: [0.5, 0, 0] # weights for distance, sparsity, coherence penalties
  feature_weights: False