spartsity:  0.5
initialization: random

dataset:
  type: csv # or csv
  path: datasets/homeloan_train.xls
  continuous_features: ['ApplicantIncome','CoapplicantIncome','LoanAmount', 'Loan_Amount_Term', 'Credit_History']
  categorical_features: ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area']
  target: Loan_Status

feature_manager:
  categorical_features:
    encoding: onehot # freqhot
  continuous_features:
    normalization: standard #minmax

constraints_file: config/constraints_conf_no.json

model:
  model_type: classification
  model_backend: sklearn
  state: pretrained
  name: LogisticRegression
  path: models/homeloan_logistic_model.pkl